### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by JStika** [arambalakjian/DataObject-as-Page#54]
Hi,

I detected strange behaviour of DOAP.
When I create my classes under /mysite/Training, it does work, but when I create under site root  "/Training" (as /cms,/framework) does not work.
Why?

**Comment by dhensby** [comment]
@JStika If you're creating the folder in the webroot as per the [framework docs](http://doc.silverstripe.org/en/developer_guides/extending/modules) then you need to do a `?flush` and the new classes will be picked up and work as expected.

Closing as I don't believe there is any bug about classes having to be in mysite
