### ISSUE TITLE
SS 3.1.10 Update - Issue with Published DOAP Items.

### ISSUE THREAD

**Issue by aledbrown** [arambalakjian/DataObject-as-Page#59]
Just a heads up for anyone updating...

I've just updated an offline site to SS 3.1.10 to check it was good to go live. It doesn't seem to like DOAP.

I did some testing:
If you create a new DOAP entry through the CMS it works fine and is fully editable in Draft mode. Press Publish and it publishes but the CMS doesn't update the screen to say it was published. Go back to the listing screen and click to edit the now published Item and it throws a PHP console error and you don't get to see the Edit form in the CMS anymore:
PHP Fatal error:  Call to a member function FormName() on a non-object in /framework/forms/FormField.php on line 167

Anyone else seeing this issue?

I've checked back through Git and that line in FormField was not changed in the latest SS update.

Standard DataObjects and Pages aren't having the issue.

Rolling back to SS 3.1.9. Confirmed all DOAPs now work again in SS 3.1.9.

**Comment by dhensby** [comment]
Fix incoming

**Comment by aledbrown** [comment]
I've just tested the fix with SS 3.1.10 update. DOAP is working perfectly again. Many thanks.
