### ISSUE TITLE
Upgrade path from Silverstripe 3 to 4 with DOAP?

### ISSUE THREAD

**Issue by aledbrown** [arambalakjian/DataObject-as-Page#69]
Hi

Is there a best practice for upgrading websites that were built on SS3 using DOAP and now need upgrading to SS4?

Thanks

**Comment by dhensby** [comment]
Basically, converty your DOAP to a page, because pages can now be managed as DataObjects in a grid field using [lumberjack](https://github.com/silverstripe/silverstripe-lumberjack)

**Comment by aledbrown** [comment]
Thank you, that's brilliant. Much appreciated.
